version: '3.9'

services:
  bot:
    build: .
    environment:
      BINANCE_API_KEY: ${BINANCE_API_KEY}
      BINANCE_API_SECRET: ${BINANCE_API_SECRET}
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN:-}
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID:-}
      TELEGRAM_ALERTS_ENABLED: ${TELEGRAM_ALERTS_ENABLED:-0}
      DOTNET_ENVIRONMENT: Production
    volumes:
      - ./logs:/app/logs
      - ./appsettings.Production.json:/app/appsettings.Production.json:ro
  seq:
    image: datalust/seq:latest
    environment:
      ACCEPT_EULA: "Y"
    ports:
      - "5341:80"
    volumes:
      - seq-data:/data

volumes:
  seq-data:
