name: Feature Request
description: Suggest an idea
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem are you facing?
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      description: How would you like to see it solved?
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Other options you considered
